### ISSUE TITLE
Solved js files for exercises in with main files

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/js-async-study#2]
The files for short_orders, cake, and cake_async are in the folder in the master branch with solutions to the exercises meant to be completed. Are these meant to be on their own branch "solutions"?

**Comment by jrhorn424** [comment]
Agreed. Thanks!

**Comment by RealWeeks** [comment]
@jrhorn424 legacy issue? I'm going to close. Please reopen if you feel it is not.
