### ISSUE TITLE
Move this lesson to the Node unit.

### ISSUE THREAD

**Issue by tdyer** [ga-wdi-boston/js-async-study#3]
Believe the lesson is OK for understanding sync vs async but Jeff Horn made a good case for not needed to know async before Ajax.

I gave this lesson to avoid confusion about when changes made in callback functions are available. For example, students were trying to access data returned from the server in code that's executed right after the  $.ajax method.

Jeff suggested that we simply say something to the effect, (We don't know when the callback is actually run so we can't count on the data from the server or the changes made in the callback). This approach seems fine to me.

AJAX needs lots of practice. Better to focus on more Ajax practice then dig into async at this time in the schedule.

**Comment by jrhorn424** [comment]
Thanks for filing this @tdyer. This captures our discussion accurately.

**Comment by jrhorn424** [comment]
I'm not sure how many times this has been delivered since Tom recorded this issue. @gaand Do you think it fits nicely with our current AJAX lessons or would it be more appropriate before Promises in Unit 3?

**Comment by gaand** [comment]
I think this topic needs repeated explication. 
I think unit one before/with Ajax is the place to start.

**Comment by gaand** [comment]
If it were still a lesson I might feel differently.

**Comment by jrhorn424** [comment]
Ok, can we close this for now?

**Comment by gaand** [comment]
Starting early (JS in browser land) and revisiting along the way (JS in node land).
