### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/js-async-study#5]
e.g. https://www.codeschool.com/blog/2014/10/30/understanding-node-js/

**Comment by jrhorn424** [comment]
Any others?

**Comment by gaand** [comment]
@ga-wdi-boston/core links?

**Comment by RealWeeks** [comment]
@gaand that link was added in commit b056e62

**Comment by gaand** [comment]
@J-Weeks Are there other links we should add?

**Comment by RealWeeks** [comment]
@gaand https://blog.risingstack.com/node-hero-async-programming-in-node-js/ i like it but I worry that some of it may be too above their head. But good side is that it has the event loop video in it as well.

**Comment by RealWeeks** [comment]
maybe this up until fibers: https://www.discovermeteor.com/blog/understanding-sync-async-javascript-node/

**Comment by RealWeeks** [comment]
This video is good too but alot it goes over the event loop pretty heavily, if we don't mind them getting that info twice it's pretty good. https://www.youtube.com/watch?v=vMfg0xGjcOI

**Comment by RealWeeks** [comment]
Thoughts before I change?

**Comment by RealWeeks** [comment]
@ga-wdi-boston/core

**Comment by gaand** [comment]
I haven't had time to curate these.  I'll accept your best judgement and if I disagree after the fact, I'll yell at you after you're gone :robot: :smile:
